name: test personal license
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        unity-version:
          - 2021.3.23f1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Request .alf file 🔑
        id: alfFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ matrix.unity-version }}
     
      - name: Activate unity
        id: ulfFile
        uses: ./
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
          unity-alf-path: ${{ steps.alfFile.outputs.filePath  }}  

      - name: Access ULF_OUTPUT
        run: echo ${{ steps.ulfFile.outputs.filePath }} 

      - name: Read ulf
        id: ulfRead
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ${{ steps.ulfFile.outputs.filePath }}

      # - name: Update secret UNITY_LICENSE
      #   uses: hmanzur/actions-set-secret@v2.0.0
      #   with:
      #     name: 'UNITY_LICENSE'
      #     value: '${{ steps.ulfRead.outputs.content }}'
      #     token: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload as artifact
        uses: actions/upload-artifact@v2  # 要用到upload-artifact@v2
        with:
          name: ${{ steps.ulfFile.outputs.filePath }}
          path: ${{ steps.ulfFile.outputs.filePath }}
          retention-days: 1