name: test personal license
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        unity-version:
          - 2021.3.23f1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Request .alf file 🔑
        id: alfFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ matrix.unity-version }}
      - name: Access ALF_OUTPUT
        run: echo ${{ steps.alfFile.outputs.filePath  }}  # 直接使用 steps 输出
      - name: Activate unity
        uses: ./
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
          unity-alf-path: ${{ steps.alfFile.outputs.filePath  }}  # 直接使用 steps 输出
