name: test personal license
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        unity-version:
          - 2021.3.23f1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Request .alf file 🔑  # 添加 request_alf 作业的步骤
        id: alfFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ matrix.unity-version }}
        env:
           ALF_OUTPUT: ${{ steps.alfFile.outputs.alf }}
      - name: Activate unity
        uses: ./
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-authenticator-key: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
          unity-alf-path: ${{ env.ALF_OUTPUT }}
